### ISSUE TITLE
Eingabe erlaubt Ziffern und Sonderzeichen

### ISSUE THREAD

**Issue by FabioFlunder** [Z1Epime/esWordle#8]
Worte sollten keine Ziffern und Sonderzeichen enthalten. " :(((( " ist kein Wort.
Am besten sollte das direkt bei der Eingabe abgefangen werden, d.h. dass diese Zeichen gar nicht erst in der Textbox auftauchen

**Comment by Z1Epime** [comment]
Implemented with #7
